spring:
  application:
    name: application
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}

data:
  mongodb:
      uri=${ROBERT_SERVER_DB_URI:mongodb\://${ROBERT_SERVER_DB_HOST:localhost}\:${ROBERT_SERVER_DB_PORT:27017}/${ROBERT_SERVER_DB_NAME:protectedRobertDB}}

server:
  port: 8086

controller:
  path:
    prefix: /api/v1

robert:
  crypto:
    server:
      # The hostname of the crypto server
      host: localhost
      # The port of the crypto server
      port: 9090

  status:
    server:
      number:
        epoch:
          oneday: 4
        next:
          days: 4
        hours: 24


  captcha:
    server:
      secret: captcha
      hostname: stopc.gouv.fr
      verify:
        url:  https://www.google.com/recaptcha/api/siteverify

  register:
    server:
      number:
        epoch: 4
        hours: 24
        day: 4

  report:
    server:
      token:
        short:
          size: 6
          type: "6-alphanum"
        long:
          size: 36
          type: "UUIDv4"

# Submission code server
submission:
  code:
    server:
      host: localhost
      port: 8087
      verify:
        path: /api/v1/verify








