spring:
  application:
    name: application
  data:
    mongodb:
        uri=${ROBERT_SERVER_DB_URI:mongodb\://${ROBERT_SERVER_DB_HOST:localhost}\:${ROBERT_SERVER_DB_PORT:27017}/${ROBERT_SERVER_DB_NAME:protectedRobertDB}}

server:
  port: ${ROBERT_SERVER_PORT:8086}

controller:
  path:
    prefix: /api/v1

robert:
  crypto:
    server:
      # The hostname of the crypto server
      host: ${ROBERT_CRYPTO_SERVER_HOST:localhost}
      # The port of the crypto server
      port: ${ROBERT_CRYPTO_SERVER_PORT:9090}

  captcha:
    server:
      secret: ${CAPTCHA_SECRET:captcha}
      hostname: ${CAPTCHA_HOSTNAME:stopc.gouv.fr}
      verify:
            url: ${VERIFY_URL:https://www.google.com/recaptcha/api/siteverify}

  report:
    server:
      token:
        short:
          size: 6
          type: "6-alphanum"
        long:
          size: 36
          type: "UUIDv4"

# Submission code server
submission:
  code:
    server:
      host: ${SUBMISSION_CODE_SERVER_HOST:localhost}
      port: ${SUBMISSION_CODE_SERVER_PORT:8087}
      verify:
        path: /api/v1/verify








