server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/protectedRobertDB

captcha:
  hostname: stopc.gouv.fr
  secret: 123456
  verify-url: https://www.google.com/recaptcha/api/siteverify

debug: false

robert:
  server:
    controller-path-prefix: /api/v1
  crypto:
      hostname: localhost
      port: 9090

submissionCode:
    server:
      hostname: localhost
      port: 8087
      verify-path: /api/v1/verify